name: eloro_app_for_home_work
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  top_snackbar_flutter: ^3.3.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  freezed: ^3.0.0-0.0.dev

flutter:
  uses-material-design: true
